### PR TITLE
Validation - Inputs

### PR DESCRIPTION
**Pull request by chrisvrose**
Dont allow invalid input. It will be reported as an error. 

Eg. Reference output (field names not from PR)

```json
{
  "ok": false,
  "response": {
    "field1": "size must be between 9 and 127",
    "field2": "size must be between 8 and 12"
  },
  "message": "Bad Input"
}
```

### CODE REVIEW

**Comment by chrisvrose** [comment]
todo add test

**Review by Prajwalprakash3722 — APPROVED** [review]
LGTM

**Comment by Prajwalprakash3722** [comment]
When do u think is a good time to move this to prod?

**Comment by chrisvrose** [comment]
Excellent question

**Comment by chrisvrose** [comment]
Let's revisit the plan to rollout if we need to.

**Comment by Prajwalprakash3722** [comment]
Sure, September end is fine?

**Pull request merged**
