### PR TITLE
Execom

### LINKED ISSUE #8: Implement Execom API
Add Execom API. Includes:
- All APIs
- corresponding validations
- UTs

### PR DESCRIPTION
**Pull request by chrisvrose**
Implement execom API.
### Reference document
Reference document - [api-spec.md](https://github.com/IEEE-RVCE/site-rear/blob/master/docs/api-ref.md#execom)
### Key differences

Member UUID doesn't have much importance. Removing it.

#### API
- [x] Create new
- [x] Update by **id**
- [x] Delete by **id**
- [x] End tenure for society
- [x] end tenure for all
- [X] Get all
- [x] Get current for execom
- [x] get past execom (with different structure)

closes #8

### CODE REVIEW

**Comment by chrisvrose** [comment]
Blocked by #11 - The modelmapper code is required to work with dtos

**Comment by Prajwalprakash3722** [comment]
a endpoint for ending the Execom would be also great.

**Comment by chrisvrose** [comment]
Agreed. I missed that one.

**Review by Prajwalprakash3722 — APPROVED** [review]
LGTM 👌🏼👍🏼

**Pull request merged**
